server:
  port: 9090
spring:
  application:
    name: counsellor-service
  datasource:
    url: jdbc:mysql://localhost:3306/counsellor?createDatabaseIfNotExist=true
    username: root
    password: Emami@4321
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
